name: Build HelloWorld

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Install GCC
        run: |
          sudo apt update
          sudo apt install -y gcc libatomic1
      - name: Checkout repository
        uses: actions/checkout@v4

      

      - name: Compile helloworld.c
        run: |
          gcc helloworld.c -o helloworld
          ./helloworld
